services:

  api:
    build:
      context: ../../
      dockerfile: Dockerfile.api.gpu
    container_name: careerpilot-api
    depends_on:
      - redis
    environment:
      MONGO_URI: ${MONGO_URI}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      GEMINI_MODEL: ${GEMINI_MODEL}
      LOG_LEVEL: ${LOG_LEVEL}
      GIT_PYTHON_REFRESH: quiet
      GEMINI_VISION_MODEL: ${GEMINI_VISION_MODEL}
    ports:
      - "8585:8585"
    networks:
      - careerpilot-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  
    runtime: nvidia          

  ui:
    build:
      context: ../../
      dockerfile: Dockerfile.ui
    container_name: careerpilot-ui
    depends_on:
      - api
    environment:
      BACKEND_URL: http://api:8585
    ports:
      - "8501:8501"
    networks:
      - careerpilot-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"  

#  agent:
#      build:
#        context: ../../
#        dockerfile: Dockerfile.agent
#      container_name: careerpilot-agent
#      depends_on:
#        - mongo
#        - redis
#      environment:
#        MONGO_URI: mongodb://mongo:27017/careerpilot
#        REDIS_HOST: redis
#        REDIS_PORT: 6379
#        GEMINI_API_KEY: ${GEMINI_API_KEY}
#        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
#        GEMINI_MODEL: ${GEMINI_MODEL}
#        LOG_LEVEL: ${LOG_LEVEL}
#        GIT_PYTHON_REFRESH: quiet
#        GEMINI_VISION_MODEL: ${GEMINI_VISION_MODEL}
#      networks:
#        - careerpilot-net
#      logging:
#        driver: json-file
#        options:
#          max-size: 10m
#          max-file: 3  
        

  #mongo:
  #  image: mongo:6
  #  container_name: mongo
  #  restart: always
  #  volumes:
  #    - ../../data/mongo:/data/db
  #    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #  ports:
  #    - "27017:27017"
  #  networks:
  #    - careerpilot-net
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-size: "20m"
  #      max-file: "5"  

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ../../data/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - careerpilot-net
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"  

networks:
  careerpilot-net:
    driver: bridge
